version: "3.8"

services:
  clent:
    image: davidsbg11/timereport-client:latest
    ports:
      - "5173:5173"
 

  server:
    image: 'davidsbg11/timereport-server:latest'
    ports:
      - "8080:8080"
  
  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017  

volumes:
  mongo_data:          
