version: "3.8"

services:
  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  server:
    image: 'davidsbg11/timereport-server:latest'
    ports:
      - "8080:8080"
    depends_on:
      - db
  clent:
    image: davidsbg11/timereport-client:latest
    ports:
      - "5173:5173"

volumes:
  mongo_data:
